from PyQt5 import QtCore, QtGui, QtWidgets


class DataTable:
    def __init__(self, parent) -> None:
        self.inputDataTable = QtWidgets.QTableWidget(parent)
        self.inputDataTable.setEnabled(False)
        self.inputDataTable.setColumnCount(8)
        self.inputDataTable.setRowCount(24)

        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputDataTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()

        self.inputDataTable.setHorizontalHeaderItem(7, item)

        # item row definition
        item = self.inputDataTable.verticalHeaderItem(0)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(0)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(2)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(3)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(4)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(5)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(6)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(7)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(8)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(9)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(10)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(11)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(12)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(13)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(14)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(15)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(16)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(17)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(18)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(19)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(20)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(21)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(22)
        item.setText("New Row")
        item = self.inputDataTable.verticalHeaderItem(23)
        item.setText("New Row")

        # item column definition
        item = self.inputDataTable.horizontalHeaderItem(0)
        item.setText("New Column")
        item = self.inputDataTable.horizontalHeaderItem(1)
        item.setText("New Column")
        item = self.inputDataTable.horizontalHeaderItem(2)
        item.setText("New Column")
        item = self.inputDataTable.horizontalHeaderItem(3)
        item.setText("New Column")
        item = self.inputDataTable.horizontalHeaderItem(4)
        item.setText("New Column")
        item = self.inputDataTable.horizontalHeaderItem(5)
        item.setText("New Column")
        item = self.inputDataTable.horizontalHeaderItem(6)
        item.setText("New Column")
        item = self.inputDataTable.horizontalHeaderItem(7)
        item.setText("New Column")
